"""
Report Generator — Automated Inspection Reports via VLM
=========================================================
Generates structured HTML/JSON inspection reports from images.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Any


class ReportGenerator:
    """Generate automated defect inspection reports.

    Combines VLM analysis with detection results to produce
    structured inspection reports in JSON and HTML formats.
    """

    def __init__(self, copilot: Any) -> None:
        self.copilot = copilot

    def generate_from_bytes(self, image_bytes: bytes) -> dict[str, Any]:
        """Generate report from raw image bytes."""
        assessment = self.copilot.assess_quality(image_bytes)

        report = {
            "report_id": f"RPT-{datetime.now(UTC).strftime('%Y%m%d%H%M%S')}",
            "timestamp": datetime.now(UTC).isoformat(),
            "assessment": assessment,
            "pass_fail": "FAIL" if assessment.get("defect_found") else "PASS",
            "severity": assessment.get("severity", "unknown"),
            "inspector": "FD-YOLO11 + VLM Copilot",
            "model_version": self.copilot.model_name,
        }

        return report

    def generate_from_path(self, image_path: str | Path) -> dict[str, Any]:
        """Generate report from image file path."""
        with open(image_path, "rb") as f:
            return self.generate_from_bytes(f.read())

    def to_html(self, report: dict[str, Any]) -> str:
        """Convert report to HTML format."""
        severity_colors = {
            "critical": "#dc3545",
            "high": "#fd7e14",
            "medium": "#ffc107",
            "low": "#28a745",
            "none": "#6c757d",
        }
        color = severity_colors.get(report.get("severity", ""), "#6c757d")

        html = f"""<!DOCTYPE html>
<html>
<head><title>Inspection Report {report['report_id']}</title>
<style>
body {{ font-family: 'Inter', sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; }}
.header {{ background: linear-gradient(135deg, #1a1a2e, #16213e); color: white; padding: 2rem; border-radius: 12px; }}
.badge {{ display: inline-block; padding: 4px 12px; border-radius: 20px; font-weight: bold; color: white; background: {color}; }}
.section {{ margin: 1.5rem 0; padding: 1rem; border-left: 4px solid {color}; background: #f8f9fa; border-radius: 0 8px 8px 0; }}
</style></head>
<body>
<div class="header">
  <h1>🔍 Inspection Report</h1>
  <p>ID: {report['report_id']} | {report['timestamp']}</p>
</div>
<h2>Result: <span class="badge">{report['pass_fail']}</span></h2>
<div class="section">
  <h3>Severity: <span class="badge">{report.get('severity', 'N/A')}</span></h3>
  <p>{report.get('assessment', {}).get('raw_assessment', 'N/A')}</p>
</div>
<p><em>Generated by {report.get('inspector', 'Chigma')}</em></p>
</body></html>"""
        return html
